### ISSUE TITLE
How do you build this?

### ISSUE THREAD

**Issue by lakner** [MeneDev/yubi-oath-vpn#14]
Hi,
I'm trying to build the project but have no idea how to do this. Where do I start?
- Stephanie :)

**Comment by MeneDev** [comment]
The build pipeline is on circle ci, and it hopefully still builds over there.

The truth is in:
https://github.com/MeneDev/yubi-oath-vpn/blob/master/.circleci/config.yml

the most important line is:

`go build -o release/yubi-oath-vpn-linux_amd64 -ldflags="-s -w -X \"main.Version=${tag:-not a release}\" -X \"main.BuildDate=$(date --utc)\" -X \"main.BuildNumber=$CIRCLE_BUILD_NUM\" -X \"main.BuildCommit=$CIRCLE_SHA1\"" -v github.com/MeneDev/yubi-oath-vpn/cmd/yubi-oath-vpn`

(the `-X` params should be optional)

And I'm not sure if things break for more recent versions of go, as they changed the module system, whereas the build still relies on `dep`. But If you use the Docker image build from https://github.com/MeneDev/yubi-oath-vpn/blob/master/builder2/Dockerfile you should be fine. The image is also on docker hub `menedev/yubi-oath-vpn-builder:006edbd626f368f1713773e2258abe38535c8074` (`006edbd626f368f1713773e2258abe38535c8074` is the commit sha of the latest release)

Hope that helps and greetings :)

**Comment by lakner** [comment]
Thanks, it works :)
