### ISSUE TITLE
Not working if multiple smart card readers available

### ISSUE THREAD

**Issue by kiview** [MeneDev/yubi-oath-vpn#5]
I'm getting the following error on my Lenovo W530 when inserting the Yubikey:
```
Using reader: Lenovo Integrated Smart Card Reader 00 00
Error Connect: scard: No smart card inserted.
```

**Comment by MeneDev** [comment]
Yes, current implementation just takes first. First with yubi in name should work. A list of names sould be in ykman. Can fix next week, currently on Rock Harz 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
